title: Advances in Turbulence Modelling
tagline: 'A joint effort by University of Michigan and NASA'
description: 'A joint effort by University of Michigan and NASA'
meta_description: "Discuss the state-of-the-art in turbulence modeling"
url: http://turbgate.engin.umich.edu/symposium

markdown: redcarpet
highlighter: pygments
logo: false
baseurl: /symposium/
domain_name: 'http://turbgate.engin.umich.edu'
google_analytics: 'UA-XXXXXXXX-X'
gems: []

# Details for the RSS feed generator
permalink: pretty


author:
  name: 'CASLAB'
  url: 'http://umich.edu/~caslab'